#!/bin/bash
set -o nounset -o pipefail -o errexit

if [ ! -f "$(dirname "$0")/.env" ]; then
    echo ".env not found"
    exit 1
fi

# Load all variables from .env and export them all for Ansible to read
set -o allexport
source "$(dirname "$0")/.env"
set +o allexport

# Run Ansible
exec ansible-playbook -i inventory.ini "$@"
