---

- name: Common
  hosts: all
  user: root
  roles: ['common']
  tags: ['common']
  handlers:
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

- name: Database
  hosts: db
  user: root
  roles: ['db']
  tags: ['db']
  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

- name: Applications
  hosts: apps
  user: root
  roles: ['apps']
  tags: ['apps']
