---

- name: Common
  hosts: all
  user: root
  roles: ['common']
  tags: ['common']

- name: Database
  hosts: db
  user: root
  roles: ['db']
  tags: ['db']
  handlers:
    - name: Restart MySQL
      systemd:
        name: mysql
        state: restarted

- name: Applications
  hosts: apps
  user: root
  roles: ['apps']
  tags: ['apps']
