---

- name: Install ufw
  apt:
    name:
      - ufw
      - fail2ban
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Deny everything
  ufw: policy=deny

- name: Set firewall rules for SSH
  ufw: rule=allow port=ssh proto=tcp

- name: Copy fail2ban sshd configuration
  copy:
    src: sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart fail2ban

- name: Harden sshd
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp | default(omit) }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "sshd -t -f %s"
  notify: Restart sshd
  with_items:
    - line: "Protocol 2"
    - line: "Protocol 1"
      state: "absent"
    #- regexp: "^Port\ "
    #  line: "Port {{ ssh_port }}"
    #- regexp: "^PermitRootLogin\ "
    #  line: "PermitRootLogin no"
    - regexp: "^AuthenticationMethods\ "
      line: "AuthenticationMethods publickey"
    - regexp: "^PasswordAuthentication\ "
      line: "PasswordAuthentication no"
    - regexp: "^PermitEmptyPasswords\ "
      line: "PermitEmptyPasswords no"
    - regexp: "^StrictModes\ "
      line: "StrictModes yes"
    - regexp: "^IgnoreRhosts\ "
      line: "IgnoreRhosts yes"
    - regexp: "^ClientAliveInterval\ "
      line: "ClientAliveInterval 300"
    - regexp: "^ClientAliveCountMax\ "
      line: "ClientAliveCountMax 0"
    - regexp: "^AllowTcpForwarding\ "
      line: "AllowTcpForwarding no"
    - regexp: "^X11Forwarding\ "
      line: "X11Forwarding no"
    - regexp: "^KexAlgorithms\ "
      line: "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
    - regexp: "^Ciphers\ "
      line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    - regexp: "^MACs\ "
      line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

- name: Enable UFW
  ufw: state=enabled

- name: Enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
